IA64: use tdep_find_unwind_table() in coredump lib
Fixup commit d93d96ad833390519ea68a2df22dd55dd26a3214 ("Fix compilation
on IA64"), and replace the dwarf_find_unwind_table() call with
tdep_find_unwind_table().

Fixes linkage error on IA64:
../src/.libs/libunwind-coredump.so: undefined reference to `dwarf_find_unwind_table'